wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.7
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      4: 3.6.7
      5: 0.10.17
alpha:
  desc: null
  value: 5
beta:
  desc: null
  value: 0.01
env:
  desc: null
  value: PandaReacher
epsilon:
  desc: null
  value: 0.0002
eval_single_agent:
  desc: null
  value: 1
factorC:
  desc: null
  value: 0.3
lambda_max:
  desc: null
  value: 15.0
method:
  desc: null
  value: MCF
num_agents:
  desc: null
  value: 5
num_steps:
  desc: null
  value: 1000000
prior_method:
  desc: null
  value: APF
project_log:
  desc: null
  value: GPO_2021
reward:
  desc: null
  value: sparse
seed:
  desc: null
  value: 0
sigma_prior:
  desc: null
  value: 0.4
target_entropy:
  desc: null
  value: -8.0
target_kl_div:
  desc: null
  value: 0.01
task:
  desc: null
  value: manipulation
use_auto_alpha:
  desc: null
  value: 0
use_auto_beta:
  desc: null
  value: 0
use_ensemble:
  desc: null
  value: 0
use_entropy:
  desc: null
  value: 1
use_kl:
  desc: null
  value: 0
use_kl_and_entropy:
  desc: null
  value: 0
